using System.Collections.Generic;

namespace PolyhydraGames.Valheim.Plugin.Extensions
{
    public static class RpcCommandMap
    {
        public static readonly Dictionary<RpcCommand, string> Names = new()
        {
            {
                RpcCommand.SetGuardianPower,"RPC_SetGuardianPower" },
            {RpcCommand.UseGuardianPower,"RPC_UseGuardianPower" },
            { RpcCommand.PeerInfo, "RPC_PeerInfo" },
            { RpcCommand.NetTime, "RPC_NetTime" },
            { RpcCommand.ServerHandshake, "RPC_ServerHandshake" },
            { RpcCommand.ClientHandshake, "RPC_ClientHandshake" },
            { RpcCommand.ServerSyncedPlayerData, "RPC_ServerSyncedPlayerData" },
            { RpcCommand.Disconnect, "RPC_Disconnect" },
            { RpcCommand.Error, "RPC_Error" },
            { RpcCommand.Kick, "RPC_Kick" },
            { RpcCommand.Kicked, "RPC_Kicked" },
            { RpcCommand.Ban, "RPC_Ban" },
            { RpcCommand.Unban, "RPC_Unban" },
            { RpcCommand.AdminList, "RPC_AdminList" },
            { RpcCommand.Save, "RPC_Save" },
            { RpcCommand.SavePlayerProfile, "RPC_SavePlayerProfile" },
            { RpcCommand.PlayerList, "RPC_PlayerList" },
            { RpcCommand.PrintBanned, "RPC_PrintBanned" },
            { RpcCommand.RemoteCommand, "RPC_RemoteCommand" },
            { RpcCommand.RemotePrint, "RPC_RemotePrint" },

            { RpcCommand.SpawnObject, "RPC_SpawnObject" },
            { RpcCommand.DestroyZDO, "RPC_DestroyZDO" },
            { RpcCommand.RequestZDO, "RPC_RequestZDO" },
            { RpcCommand.ZDOData, "RPC_ZDOData" },
            { RpcCommand.RoutedRPC, "RPC_RoutedRPC" },
            { RpcCommand.SetTrigger, "RPC_SetTrigger" },

            { RpcCommand.Heal, "RPC_Heal" },
            { RpcCommand.Damage, "RPC_Damage" },
            { RpcCommand.Stagger, "RPC_Stagger" },
            { RpcCommand.UseStamina, "RPC_UseStamina" },
            { RpcCommand.OnDeath, "RPC_OnDeath" },
            { RpcCommand.OnTargeted, "RPC_OnTargeted" },
            { RpcCommand.FlashShield, "RPC_FlashShield" },
            { RpcCommand.AddStatusEffect, "RPC_AddStatusEffect" },
            { RpcCommand.Controls, "RPC_Controls" },
            { RpcCommand.ReleaseControl, "RPC_ReleaseControl" },
            { RpcCommand.RequestControl, "RPC_RequestControl" },
            { RpcCommand.RequestRespons, "RPC_RequestRespons" },

            { RpcCommand.ChatMessage, "RPC_ChatMessage" },
            { RpcCommand.TeleportPlayer, "RPC_TeleportPlayer" },
            { RpcCommand.Say, "RPC_Say" },

            { RpcCommand.DropItem, "RPC_DropItem" },
            { RpcCommand.DropItemByName, "RPC_DropItemByName" },
            { RpcCommand.RequestOwn, "RPC_RequestOwn" },
            { RpcCommand.SetPose, "RPC_SetPose" },
            { RpcCommand.SetVisualItem, "RPC_SetVisualItem" },
            { RpcCommand.OpenRespons, "RPC_OpenRespons" },
            { RpcCommand.RequestStack, "RPC_RequestStack" },
            { RpcCommand.StackResponse, "RPC_StackResponse" },
            { RpcCommand.RequestOpen, "RPC_RequestOpen" },
            { RpcCommand.RequestTakeAll, "RPC_RequestTakeAll" },
            { RpcCommand.TakeAllRespons, "RPC_TakeAllRespons" },
            { RpcCommand.AddFuel, "RPC_AddFuel" },
            { RpcCommand.AddItem, "RPC_AddItem" },
            { RpcCommand.RemoveDoneItem, "RPC_RemoveDoneItem" },
            { RpcCommand.SetSlotVisual, "RPC_SetSlotVisual" },
            { RpcCommand.AddFuelAmount, "RPC_AddFuelAmount" },
            { RpcCommand.SetFuelAmount, "RPC_SetFuelAmount" },
            { RpcCommand.ToggleOn, "RPC_ToggleOn" },
            { RpcCommand.Pickup, "RPC_Pickup" },
            { RpcCommand.RequestPickup, "RPC_RequestPickup" },

            { RpcCommand.UseDoor, "RPC_UseDoor" },
            { RpcCommand.Repair, "RPC_Repair" },
            { RpcCommand.Remove, "RPC_Remove" },
            { RpcCommand.HealthChanged, "RPC_HealthChanged" },
            { RpcCommand.UpdateMaterial, "RPC_UpdateMaterial" },
            { RpcCommand.SetAreaHealth, "RPC_SetAreaHealth" },

            { RpcCommand.SetEvent, "RPC_SetEvent" },
            { RpcCommand.BossSpawnInitiated, "RPC_BossSpawnInitiated" },
            { RpcCommand.RemoveBossSpawnInventoryItems, "RPC_RemoveBossSpawnInventoryItems" },
            { RpcCommand.SpawnBoss, "RPC_SpawnBoss" },

            { RpcCommand.SetTamed, "RPC_SetTamed" },
            { RpcCommand.ResetCloth, "RPC_ResetCloth" },
            { RpcCommand.FreezeFrame, "RPC_FreezeFrame" },
            { RpcCommand.OnHit, "RPC_OnHit" },
            { RpcCommand.Attach, "RPC_Attach" },
            { RpcCommand.TeleportTo, "RPC_TeleportTo" },
            { RpcCommand.StaggerCreature, "RPC_Stagger" },
            { RpcCommand.OnEat, "RPC_OnEat" },
            { RpcCommand.TryEat, "RPC_TryEat" },
            { RpcCommand.EatConfirmation, "RPC_EatConfirmation" },
            { RpcCommand.Nibble, "RPC_Nibble" },
            { RpcCommand.Step, "RPC_Step" },
            { RpcCommand.Wakeup, "RPC_Wakeup" },
            { RpcCommand.Grow, "RPC_Grow" },
            { RpcCommand.Shake, "RPC_Shake" },
            { RpcCommand.Command, "RPC_Command" },
            { RpcCommand.UnSummon, "RPC_UnSummon" },
            { RpcCommand.SetName, "RPC_SetName" },

            { RpcCommand.Forward, "RPC_Forward" },
            { RpcCommand.Backward, "RPC_Backward" },
            { RpcCommand.Rudder, "RPC_Rudder" },
            { RpcCommand.Stop, "RPC_Stop" },
            { RpcCommand.AddSaddle, "RPC_AddSaddle" },
            { RpcCommand.RemoveSaddle, "RPC_RemoveSaddle" },
            { RpcCommand.SetSaddle, "RPC_SetSaddle" },
            { RpcCommand.RequestControlShip, "RPC_RequestControl" },
            { RpcCommand.ReleaseControlShip, "RPC_ReleaseControl" },

            { RpcCommand.SetGlobalKey, "RPC_SetGlobalKey" },
            { RpcCommand.RemoveGlobalKey, "RPC_RemoveGlobalKey" },
            { RpcCommand.GlobalKeys, "RPC_GlobalKeys" },
            { RpcCommand.LocationIcons, "RPC_LocationIcons" },
            { RpcCommand.AddNoise, "RPC_AddNoise" }
        };
    }
}